### ISSUE TITLE
Create Content Type for Calendar Page

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#167]
- [x] Template
- [x] Data Definition
- [x] Metadata Set
- [x] Configuration Set
- [x] Base Asset
- [x] Asset Factory

**Comment by nikdragovic** [comment]
I will review this with Gretchen.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance. It's fairly simple with one field for the Trumba event calender's ID, which should be all we need in order to dynamically crank out the Calendar page.

**Comment by nikdragovic** [comment]
@laurenhamel Is there a link for me to test this, or do you recommend that I create a page? We only need one, correct?

**Comment by laurenhamel** [comment]
@nikdragovic, yes, there's only one page, and since this is a new content type and there aren't any pages just yet that use this DD (as far as I'm aware), I think the best approach would be to just create a page wherever you see fit within the IA.

**Comment by nikdragovic** [comment]
I created the page: 

https://cascade.emory.edu/entity/open.actid=43c9b7ce0ae72098508fdcfb27ce9558&type=page
 
@kristianserrano do you know where I need to pull the calendar ID from in Trumba?

**Comment by kristianserrano** [comment]
Do you have access to our (Maureen's) Trumba account? If so, do the following.

1. Log in to http://www.trumba.com
2. Go to the calendar for which you need the id.
3. Click the `Settings` button at the top.
4. Click `Edit Publishing Settings` under usage information.
5. Copy the text in the `Unique web name` field.

If you don't have access, let me know which calendars you need and I can get the IDs for you.

**Comment by nikdragovic** [comment]
@laurenhamel I am getting a 515 error here:

http://qa.libraries.emory.edu/events-and-exhibits/calendar-of-events

Is it because I am adding a Trumba feed ID when there is still some feeds work to be completed? Or am I missing something elsewhere?

**Comment by laurenhamel** [comment]
@nikdragovic, only the DD for this page type has been created at this point. The template pattern is still in the backlog (emory-libraries/pattern-library#172).

**Comment by nikdragovic** [comment]
@laurenhamel Thanks for clarifying, apologies that I missed the repo/issue details. Accepting.
