### ISSUE TITLE
Create Content Type for Form Page

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#171]
- [x] Template
- [x] Data Definition
- [x] Metadata Set
- [x] Configuration Set
- [x] Base Asset
- [x] Asset Factory

*Note: This would be a basic page that embeds a LibWizard form.

**Comment by kristianserrano** [comment]
I've got this up in Cascade, @laurenhamel.
https://cascade.emory.edu/entity/open.act?id=c62814820ae72098545b3eb790496234&type=structureddatadefinition

I'm actually debating whether this actually needs that intro paragraph.

**Comment by nikdragovic** [comment]
Reviewed and accepted on 5/22.
