### ISSUE TITLE
Define what "Video Collections" pattern means on Materials Page Figma design

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#172]
This component could be generalized if we can identify what it's actually doing. Right now, it seems to be a component for features collections, possibly linking to Finding Aids (maybe?)

Is it actually a "Collections" pattern? Do we make the entire title editable (i.e. - title of "Video Collections" vs.  collection type of "Video")?

**Comment by lovinscari** [comment]
Feedback from Kim Collins and Chris Palazzolo which I believe should clear the block -

"Dear Cari,
Correct. 
 
It is my understand that the materials template is sufficient for this Films and Video page  (https://cascade.emory.edu/entity/open.act?id=08c674340ae720980c981690deac3e2a&type=page / http://staging.libraries.emory.edu/materials/films-videos. 
 
In addition, the “research help” template will be used for this Finding Films and Video page https://cascade.emory.edu/entity/open.act?id=dad2fd4e0ae7209842afc98ccb0634f5&type=page / http://staging.libraries.emory.edu/using-the-library/find-films-and-videos (515 error in staging)
 
No separate pattern/template needs to be designed for a Video Collection page.
 
Thanks for asking,
Kim"

**Comment by kristianserrano** [comment]
I'll go ahead and close this then.
