### ISSUE TITLE
Create content type for redirects

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/web-redesign#174]
This will likely be two-fold but is largely dependent on how redirects will be implemented. Conceptually, this may look like:

1. A redirect content type at the page-level for handling internal redirects, where this content type can inserted in place of a single page if/when it gets moved or deleted.

2. A content type that allows for a list of redirects to be defined, which may live within a site's meta folder or similar and allows for external redirects to be managed

To Dos
---
- [x] Template
- [x] Data Definition
- [x] Metadata Set
- [x] Configuration Set
- [x] Base Asset
- [x] Asset Factory

**Comment by laurenhamel** [comment]
@kristianserrano, I went ahead and created this issue based on the conversation we had yesterday, but feel free to update it as you see fit, including the estimate.

**Comment by kristianserrano** [comment]
@laurenhamel I've created the page for redirects on the main site here:
https://cascade.emory.edu/entity/open.act?id=c27920b40ae72098545b3eb7c60c7b70&type=page

If you think this is good to go, feel free to move it to To Accept (or let me know and I can do it).

If we do need to remove the folder option in the end, we can add a new issue for that.

**Comment by nikdragovic** [comment]
Reviewed and accepted on 5/22.
