### ISSUE TITLE
Create template for Landing Page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#176]
- [x] Cascade CMS work
- [x] Pattern Library elements
- [x] Templating Engine work
- [x] Scripting
- [x] Code deployment

**Comment by laurenhamel** [comment]
This was completed and moved to Phase 2. However, Phase 2 has placed the use of Landing pages on hold. Pages that were slated for Landing pages are being converted to Cover pages for the time being.
