### ISSUE TITLE
Create template for Research Help Page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#192]
- [x] Cascade CMS work
- [x] Pattern Library elements
- [x] Templating Engine work
- [x] Scripting
- [x] Code deployment

**Comment by kristianserrano** [comment]
@nikdragovic Are Library Aids now officially renamed Research Help? If so, I'll need to update the data definitions, configuration sets, templates, asset factories, etc. in Cascade.

**Comment by nikdragovic** [comment]
@kristianserrano That's what our SME settled on, pending approval but I'm confident this is the final label for launch.

**Comment by laurenhamel** [comment]
This was completed and moved to Phase 2.
