### ISSUE TITLE
Implement development practices defined by the LTDS Microprocess Task Force

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#2]

**Comment by laurenhamel** [comment]
I see that the blockers for this epic have been closed, so I'm wondering if this should also be closed? To what extent does some of the testing/development process documentation that we've been creating also group back into this?

**Comment by nikdragovic** [comment]
I think the testing/dev processes relate, and are all we can feasibly hope to complete as part of this project. I think confirmation on the Microprocess work is still TBD and related more to division-level strategy. Worth discussing with Doug and Cari to confirm.

**Comment by kristianserrano** [comment]
Can we close this? Is it still an issue to resolve as part of the project per se?

**Comment by nikdragovic** [comment]
@kristianserrano I am fine with closing this. I think we should attach 40 points to it first >:)

**Comment by laurenhamel** [comment]
This is no longer applicable as we move into Phase 2 and processes/workflows continue to evolve. A new issue should probably be opened to more accurately capture the work that needs to be documented once development practices and processes have been finalized.
