### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#202]
- [ ] favicon should appear on `staging.libraries`
- [ ] favicon should appear on `prod.libraries`

**Comment by libdgg** [comment]
KS will work with James Bias to implement.

**Comment by kristianserrano** [comment]
Spoke with James. He will be configuring the favicon on the server just as it is on the standard Emory web host. He said he'll look for the one being used on that server, copy it, and configure it.

**Comment by kristianserrano** [comment]
This is in place and working. The only caveat is a naming conflict with the `/icons` folder which Apache uses as a default for its icons (redirects `/icons` on a webhost to a server folder it uses). According to James, Apache also uses the `/icons` folder for favicons.

This might require renaming the location of our icons to a different folder name. If so, I'll need to crawl through `template-sass` and `Pattern-Library` repos to change references to `/icons`.

**Comment by kristianserrano** [comment]
I’ve got the changes necessary to move `/icons`  into `/assets` to resolve the folder name conflict on Apache. The icons import from `template-sass` to the appropriate src folder in `Pattern-Library` which then generates the appropriate folder for the distribution. I’m going to wait until Monday to deploy the changes to `staging`, `preview`, and the published pattern library.

After we deploy, I'll let @jamesbiasemory know.
