### ISSUE TITLE
Create sitemap.xml format for cascade content

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#206]
## Testing

`preview` [sitemap.xml](https://preview.libraries.emory.edu/sitemap.xml)

**Comment by kristianserrano** [comment]
Publish to website root directory.

**Comment by laurenhamel** [comment]
@kristianserrano, question for you regarding the new publish configuration from Cascade. I know you mentioned setting up the a publish destination to push the `sitemap.xml` out to the website's root directory. Will the default publish locations (`dev`, `qa`, `staging`, `prod`, etc.) also exclude this file?

**Comment by kristianserrano** [comment]
No, but that didn't seem to be a problem so far, unless there's something happening behind the scenes that's causing issues.

**Comment by laurenhamel** [comment]
Tested and confirming that it works for our needs. It's also already been deployed to `preview.libraries.emory.edu/sitemap.xml`(https://preview.libraries.emory.edu/sitemap.xml), which is working as expected. @nikdragovic, can you confirm on your end and give acceptance?

**Comment by laurenhamel** [comment]
Updated with a link to the `sitemap.xml` on `preview.libraries.emory.edu`.
