### ISSUE TITLE
Create Google Analytics Property ID and add to site

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#208]

**Comment by laurenhamel** [comment]
I'm dropping a note to make sure that the work for including the GA script into the `default` layout is also captured here. We had originally captured this in emory-libraries/pattern-library#282, but since we opened this issue to break out the GA stuff separately, I removed anything related to analytics and tracking from the aforementioned issue.

**Comment by kristianserrano** [comment]
I created the property ID yesterday, added it to the site, and published the api-ids XML to dev. I can look into adding the tracking script today.

**Comment by kristianserrano** [comment]
@laurenhamel This is ready to test. I simply modified `engine/layout/default.hbs` and `engine/layout/development.hbs`.

I noticed that Google's newer tracking codes try to make use of Google Tag Manager, but this is using the previous universal tracking code. I really need to dive into GTM at some point.

**Comment by laurenhamel** [comment]
@kristianserrano, question for you regarding `development.hbs`. This template is only used for local development and the `dev` domain. Are we wanting to include tracking in these instances? I'm going to take a look now and test. 

Regarding GTM tracking versus the more traditional way of embedding the GA tracking scripts, I've mostly used GTM in the recent past, which I know offers a lot more flexibility and offers better control over testing. Setting up the tracking for the site is fairly simple, and then getting it integrated into `default.hbs` is just like using traditional GA embeds.

**Comment by laurenhamel** [comment]
@kristianserrano, also another question for you about `default.hbs`. I see that you didn't add any checks for environments (`qa` vs. `staging` vs. `prod`). Are we wanting to capture analytics for all 3 of these environments? If not, I think we may want to consider blacklisting any environments that we don't want to have tracked.

**Comment by kristianserrano** [comment]
@laurenhamel oh, I just had it in development for testing locally. I can remove it from there.

Regarding environments, I didn't even think of that. Let's discuss approaches to that.

**Comment by laurenhamel** [comment]
@kristianserrano, I think we can move this to deploy to production since it can't be tested in qa.

**Comment by kristianserrano** [comment]
Moved it.
