### ISSUE TITLE
Home page load time issue on preview.libraries.emory.edu

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/web-redesign#210]
The home page is taking over 12 seconds to load (on-campus wireless) and the hero image is not loading.

**Comment by kristianserrano** [comment]
@lovinscari this will a require a discussion with Lauren in how we might change how files are prerendered and delivered when requested. I have some ideas on how we might change our approach, including possibly prerendering static html files that are periodically and/or manually updated.

**Comment by laurenhamel** [comment]
Due to scope changes related to Phase 2 work, this will not be fixed since the templating engine is no longer in use.
