### ISSUE TITLE
Pattern Library: Update Exhibition Template

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#215]
- [x] Remove white space between Dive Deeper and Footer
- [x] Shield should span the two different blues
- [x] The two different blues should but up against each other.

[Compare Template](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-exhibition) with [Figma Design](https://www.figma.com/file/avklVGwesTU6PIw6BM1dmTvl/Pattern-Modeling?node-id=52%3A13373)

**Comment by laurenhamel** [comment]
This has been fixed. I also noticed some other slight layout and spacing issues, which I'm addressing in these same commits.
