### ISSUE TITLE
Data Definitions: Update Hours Template

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#225]
Update the data definitions to match the new design

- [x] Ensure that all the semesters are available.  Options are (Fall Term, Winter Intersession, Spring Term, Summer Term, Summer Intersession)
- [x] Content editors should be able to toggle a semester as either visible or not visible
- [x] Options for each day and exceptions should be Open, Closed, Open 24 hr
    - [x] If the building is open, the sub option Open should allow you to select a time or enter free text; times should be in 15 minute increments
    - [x] If the building is open, the sub option Closed should allow you to select a time or enter free text; times should be in 15 minute increments
- [x] Provide a method to group hours for service points by buildings.

**Comment by laurenhamel** [comment]
I updated the [Hours](https://cascade.emory.edu/entity/open.act?id=73390b500ae7209811020203ff6606e5&type=structureddatadefinition) data definition, which currently lives under Shared Site Content in the `Emory Libraries - Template Assets Cascade` site. While I didn't make any changes to the [Hours Page](https://cascade.emory.edu/entity/open.act?id=95dd142d0ae720982cb3308e022ea9fa&type=structureddatadefinition) data definition, we may want to reevaluate what this looks like from a content management standpoint and also adjust it accordingly. This may depend on whether or not Hannon Hill thinks they'll be able to utilize this content as is, leveraging the same IA structure for the hours data that currently exists (i.e., hours for each location exists in its own separate file under the `_shared/hours/` folder). I imagine that they should be able to at least create a workaround of some sort utilizing an index block (which may still mean we need to edit the Hours Page data definition to include this index block by default).

If not, though, we'll likely want to update the Hours Page data definition to resemble that of a directory page, where content editors will need to select from/link to all of the location hours (assuming that this information still lives in separate data files within the IA) that they wish to include on the Hours page. Regardless of the approach that we end up taking, I do foresee a lot of the heavy lifting still needing to be done dynamically, such as grouping by semester, calculating and extracting upcoming hours, sorting, etc.

**Comment by rosy1280** [comment]
@laurenhamel I'll try to take a look tonight.

**Comment by rosy1280** [comment]
I think it looks good, but I'll see if I can schedule a time with Colin Bragg and Oliver to get their thoughts.
