### ISSUE TITLE
Bio Page: Simple updates to the design

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#227]
- [x] Move CV.  The button on the bottom of the page isn't cutting it.  Can we move it into the sidebar?  If so where?  Should it get its own sidebar section? Just a link will do rather than a button.  Maybe a pdf icon (material-picture_as_pdf)?
- [x] Contact Header.  The sidebar where contact information is should probably have a header that says Contact.  Flaws with this?

**Comment by laurenhamel** [comment]
I went ahead and moved the CV link into the sidebar under a "Related Downloads" section. What are your thoughts on this approach, @rosy1280? 

<img width="1260" alt="Screen Shot 2019-10-08 at 12 33 48 PM" src="https://user-images.githubusercontent.com/24446243/66414795-18c7f780-e9c8-11e9-91a5-f2b8d18b1188.png">
