### ISSUE TITLE
Ensure css and js for prod.libraries is deployed appropriately

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#242]
Right now the sprites aren't appearing on `prod`, inspecting the page shows its pointing to `staging`. When offsite you can see the site without any styles.

- [x] ensure the PL deploys css, js, and other assets to `prod` and `staging`
- [x] ensure that `prod` and `staging` are both using relative links for the css and js.
- [x] ensure that all other assets (icons, images, php, etc.) are deployed to `prod` and `staging`

**Comment by laurenhamel** [comment]
@rosy1280, the `sprite.svg` is separate from the CSS and JS. I've edited the existing checklist and added another bullet point to help clarify.
