### ISSUE TITLE
Resolve CORS issue for SVG Sprite

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#247]
Find solution for SVG sprites not loading in Cascade.

**Comment by libdgg** [comment]
Assign this to James Bias.

**Comment by kristianserrano** [comment]
Followed up with James. Here's what I've found out so far.
- Caleb said, "Lots of sites have content that don't fully render without publishing."
- Caleb is wary of making a change to suit one site.
- Adds a manual process to any upgrades of Tomcat
- Possible solution:
  - Change icon macro to use relative path without conditions. It currently uses a relative path for publishing but an absolute path for viewing in Cascade.
  - Copy of SVG sprite is uploaded or edited in Cascade whenever a change is deployed.
  - Other changes to markup would require modifying macros before deployment anyway.

I'm still thinking of other possible solutions.

**Comment by kristianserrano** [comment]
Another wrench thrown in... There a naming conflict with the `/icons` folder which Apache uses as a default for its icons (redirects `/icons` on a webhost to a server folder it uses). According to James, Apache also uses the `/icons` folder for favicons.

This might require renaming the location of our icons to a different folder name. If so, I'll need to crawl through `template-sass` and `Pattern-Library` repos to change references to `/icons`.

**Comment by kristianserrano** [comment]
@rosy1280 I've copied the SVG file from `Template Assets` to `Main` (https://cascade.emory.edu/entity/open.act?id=93b5cc5a0ae7209864aeb97c3ae7d0ff&type=file) and modified the Velocity format to use the `system-asset:local` pseudo tag when viewing internally (https://cascade.emory.edu/entity/open.act?id=acc410690ae7209815168d8a9bb90a5d&type=format).

I tried to use a reference (similar to a symlink in Cascade) so that we could single-source it from `Template Assets`, but that didn't seem to work for the SVG file.

If HH would like to make modifications, they should feel free to.

**Comment by kristianserrano** [comment]
@rosy1280 James followed up with me regarding the deploy issues I mentioned during Tuesday's weekly meeting. Apparently, there's a known issue with file mounts that are accessed by Cascade and webdav in which permissions get altered. According to James, a number of customers using webdav have this issue and they periodically need to reset permissions.

**Possible solution:** James offered to set up a cron job running every 10 minutes to reset the group write permissions.

So for now, the deploy script works again. I'll add a new issue to the board to investigate solutions in the future.
