### ISSUE TITLE
Schedule a publishing job for hours

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#249]
Currently the hours page pulls the `today` variable at the time of publish (this happens because cascade is a push cms).  This variable is used to determine what day the upcoming hours date checker appears as.  In the below screenshot you can see that the page hasn't been published since Dec 3, so the date picker is still stuck there.

Scheduling a publishing job for hours should fix this issue.  Alternatively we could update the page and pull the today variable using javascript on the page.

**Comment by kristianserrano** [comment]
@rosy1280 I've set this up to publish daily at 12am using a publish set here:
https://cascade.emory.edu/entity/open.act?id=ec4bf04e0ae720980494f5dddd98af24&type=publishset

If there is a publish error, I will be notified by email.
