### ISSUE TITLE
Create robots.txt

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#250]
- [x] Create the file in Cascade for easy management and updating.
- [x] Include blocks for static pages.

**Comment by kristianserrano** [comment]
@rosy1280 the robots.txt is in place and published.

**Comment by rosy1280** [comment]
@kristianserrano update so that nothing is crawled on prod.libraries.emory.edu

**Comment by kristianserrano** [comment]
@rosy1280 this is done.
