### ISSUE TITLE
Change site URL for Main site.

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#252]
Change the site URL for the main site to `libraries.emory.edu`.

**Comment by kristianserrano** [comment]
@rosy1280 The timing on this is important as it could mess up URLs on `staging.libraries.emory.edu` and `prod.libraries.emory.edu` if we set it to `libraries.emory.edu`.

One option might be to keep it as staging, publish it there, and disable that publish destination. Then change it `prod.libraries.emory.edu` and publish to prod. Then change it to `libraries.emory.edu` and schedule a publish of the site for launch.

**Comment by kristianserrano** [comment]
Based on a conversation with @rosy1280, we're holding on this change with respect to timing.

I propose the following plan:

1. Publish to `staging` with the `staging.libraries.emory.edu` subdomain as the URL. (Already done?)
2. Disable staging as a publish destination.
3. Change the URL to `prod.libraries.emory.edu` to make sure the `prod.` subdomain version of the site functions correctly. 
4. Publish to `prod`. Note: Site search will not work as it is configured for `libraries.emory.edu` and we do not want search engines indexing `prod.libraries.emory.edu`.
5. Disable publishing to production.
6. Change the URL to `libraries.emory.edu`.
7. Reenable publishing to production.
8. On the day before launch, schedule publishing for 00:01 on morning of launch date.

**Comment by rosy1280** [comment]
based on the conversation in Website Launch meeting updating the above list to just be:

1. Disable publishing to production.
2. Change the URL to libraries.emory.edu.
3. Reenable publishing to production.
4. On the day before launch, schedule publishing for 00:01 on morning of launch date.

**Comment by kristianserrano** [comment]
I've updated the URL to `libraries.emory.edu`.

**Comment by kristianserrano** [comment]
@rosy1280  I've updated the URL to `libraries.emory.edu`.
