### ISSUE TITLE
Request DNS change

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#254]
Request that the DNS be changed from prod.libraries to simply libraries

**Comment by libdgg** [comment]
INC03290687 submitted to service now.
The new web site for Emory Libraries has been approved for launch on Tuesday January 7, 2020 at 9am. Change Request is CHG144946 This ticket is for the DNS (and any other work) needed to support the launch. The official domain for the new site will be https://libraries.emory.edu Here are notes for review from my conversations with Steve Collins to confirm or for any next steps. Please let me know if there are any questions or any next steps i can take at this time that can help with this ticket. NOTES: Preview.libraries.emory.edu resolves to 170.140.125.225 which is a VIP (virtual IP) on the F5.   The VIP on the F5 is the front door to the 2 web servers, libwebprod1 and libwebprod2. Libraries.emory.edu resolves to 170.140.205.20 which is the cascade.library.emory,edu VM (current production). When we are ready to go live, we will change libraries.emory.edu to point to 170.140.125.225 on the F5. Apache on libwebprod1/2 are configured to send any requests for preview.libraries.emory.edu and libraries.emory.edu to the same directories on the server. Therefore, sending traffic to the F5 will serve up the new content as soon as the change is made.

**Comment by rosy1280** [comment]
@libdgg requested a change for time to live to be every 5 minutes on january 6th -- INC03292602

**Comment by libdgg** [comment]
The TTL has been changed to 5 minutes. Here is the note from the ticket INC03292602

C:\Users\abowe22>nslookup libraries.emory.edu
Server:  dns1.emory.net
Address:  170.140.1.1

Name:    cascade.library.emory.edu
Address:  170.140.205.20
Aliases:  libraries.emory.edu
