### ISSUE TITLE
Republish the entire site to staging and prod

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#256]
This should be done when we are certain the site is in a place where we are ready for launch.

**Comment by rosy1280** [comment]
this should happen by December 20th.

**Comment by kristianserrano** [comment]
This coincides with [#252](https://app.zenhub.com/workspaces/website-redesign-5be9f5af4b5806bc2bf3ddda/issues/emory-libraries/web-redesign/252) (Change Site URL for Main site).
