### ISSUE TITLE
Change 404 configuration on server for production.

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#257]
Need to change config so that the 404 page works on both `prod.libraries.emory.edu` and `libraries.emory.edu`.

**Comment by rosy1280** [comment]
@jamesbiasemory will update as he opens up firewall rules.

**Comment by kristianserrano** [comment]
@jamesbiasemory Did you say in the meeting you were changing this immediately or does this still need to be done?

**Comment by jamesbiasemory** [comment]
done. 
Also opened up prod to the outside world and setup libraries.emory.edu to work, and tested it via host file. prod.libraries is still setup as a server alias.
