### ISSUE TITLE
Close access to prod and preview subdomains

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#261]
@rosy1280 if the `preview.` and `prod.` subdomains remain open after we deploy the updates robots.txt to allow crawling, it's possible for Google to index them by following the links we put up for those preview URLs. We might want to close public access to those subdomains when we prepare to republish the site to production for launch.

Related note: I've updated the sitemap.xml to use `libraries.emory.edu` as the domain and added the `.html` file extension to pages (we weren't using extensions when we first set it up).

**Comment by rosy1280** [comment]
makes sense.  so to clarify we need to:

- update the robots.txt file to allow crawling and then set a time to republish robots.txt just before launch

this ticket is asking @jamesbiasemory to move `prod` and `preview` so they aren't accessible off campus AFTER launch.  i'll assign this ticket to him and let him know via slack.

**Comment by jamesbiasemory** [comment]
I will take them out of the configs and get the domains deleted.


________________________________

**Comment by rosy1280** [comment]
thanks @jamesbiasemory !

**Comment by rosy1280** [comment]
trying to close access to prod and preview unearthed that the website is still using assets at prod.  @kristianserrano has made the necessary changes, but the site needs to be republished.  we have opted to do that later this evening via a republish job.  @rosy1280 will schedule that.  tomorrow we'll ask @jamesbiasemory to work on this ticket.
