### ISSUE TITLE
Mobile icon links not working

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-redesign#262]
Hi all, 

On the mobile site, the upper right menu icons for Events, Maps, Hours, News, and Contact are not working. 

Thanks!
Colin

![mobile menu icons.JPG](https://images.zenhubusercontent.com/5df7babf7b5b6937b5601871/a2597cae-1d64-4f8a-ac03-def3d6523301)

**Comment by kristianserrano** [comment]
@rosy1280 the fix for this is merged into master. It didn't render in the pattern library due to empty string values for hrefs; when the pattern checked for a value for href, it came up false. I added `#` to the href value in several json files in the pattern library so that they would not be empty. I'll deploy to staging and the pattern library on the morning of the 8th for testing.

I believe HH will need to modify the Velocity in Cascade here:
https://cascade.emory.edu/entity/open.act?id=ac8dfc900ae7209815168d8a9ad6b4cd&type=format

**Comment by rosy1280** [comment]
@kristianserrano can you find me a link to the commit for this?  i suspect HH will want to see it.

**Comment by rosy1280** [comment]
submitted to HH via wrike.  assigning to me so that we know i'm the one who should close ( @kristianserrano correct me if i'm wrong though)

**Comment by kristianserrano** [comment]
@rosy1280 the commit won't show the changes to the generated markup, just the changes to the JSON that stores sample data. We don't track the `public` folder that would have the generated HTML, but it's viewable in the pattern library.

HH should be able to reference the markup for the mobile nav below to know how to modify their templating. If HH needs more information, I'm more than happy to coordinate with them.

**Minor Note:** I just noticed that the mobile nav at the compounds level doesn't have links, but at the organisms level it does. I've fixed that and deploying it to the pattern library shortly in case HH wants to see it there.

```
<nav aria-label="Utility navigation" class="nav-menu-utility -mobile">
    <div class="nav-menu-utility-right">
        <a href="#" class="nav-button -flyout" tabindex="0">
            <span class="icon" aria-hidden="true" data-icon="material-event">
                <svg>
                    <use xlink:href="/styleguide/patternlibrary/current/assets/icons/sprite/sprite.svg#material-event" />
                </svg>
            </span>
            <span class="nav-button-label">Events</span>
        </a>
        <a href="#" class="nav-button -flyout" tabindex="0">
            <span class="icon" aria-hidden="true" data-icon="material-map">
                <svg>
                    <use xlink:href="/styleguide/patternlibrary/current/assets/icons/sprite/sprite.svg#material-map" />
                </svg>
            </span>
            <span class="nav-button-label">Maps</span>
        </a>
        <a href="#" class="nav-button -flyout" tabindex="0">
            <span class="icon" aria-hidden="true" data-icon="material-access_time">
                <svg>
                    <use xlink:href="/styleguide/patternlibrary/current/assets/icons/sprite/sprite.svg#material-access_time" />
                </svg>
            </span>
            <span class="nav-button-label">Hours</span>
        </a>
        <a href="#" class="nav-button -flyout" tabindex="0">
            <span class="icon" aria-hidden="true" data-icon="material-newspaper">
                <svg>
                    <use xlink:href="/styleguide/patternlibrary/current/assets/icons/sprite/sprite.svg#material-newspaper" />
                </svg>
            </span>
            <span class="nav-button-label">News</span>
        </a>
        <a href="#" class="nav-button -flyout" tabindex="0">
            <span class="icon" aria-hidden="true" data-icon="material-question_answer">
                <svg>
                    <use xlink:href="/styleguide/patternlibrary/current/assets/icons/sprite/sprite.svg#material-question_answer" />
                </svg>
            </span>
            <span class="nav-button-label">Contact</span>
        </a>
    </div>
</nav>
```
