### ISSUE TITLE
Extra parentheses in mobile site dropdown menu

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-redesign#263]
On the mobile site, there are extra parentheses between lines in the Tools dropdown menu.

![IMG_8092.PNG](https://images.zenhubusercontent.com/5df7babf7b5b6937b5601871/a5ac7927-df97-47b5-9426-11b444b8511b)

Thanks!
Colin

**Comment by kristianserrano** [comment]
@cwbragg (CC: @rosy1280) Strangely, I'm not seeing this on my phone or when using dev tools in Firefox to simulate mobile. Are you seeing it on your phone still?

## Firefox Desktop
![Screen Shot 2020-01-09 at 10.05.39 AM.png](https://images.zenhubusercontent.com/5b870487d5262f371e9eac64/fd4980cb-9a34-4bd2-96d1-28ca76e3769d)

## Chrome Android
![Screenshot_20200109-095339.png](https://images.zenhubusercontent.com/5b870487d5262f371e9eac64/117ca54f-8c7f-4cde-a5ba-5979c11516bd)

**Comment by cwbragg** [comment]
Hey, I am on both iPhones 6 and 8 in both Chrome and Safari. They appear in-between each tool line when holding it in phone/portrait mode, and then they are immediately after the tool description when holding it in landscape mode:

![IMG_8096](https://user-images.githubusercontent.com/58950697/72081264-2beeaa00-32cc-11ea-8317-6ebbb9df8556.PNG)

**Comment by kristianserrano** [comment]
Great! Thanks for confirming, @cwbragg. I'll look into it!

**Comment by kristianserrano** [comment]
@cwbragg and @rosy1280, I beleive the issue is caused by the following code in the velocity format for the main nav.

```#if($options.contains("alias")||$options.contains("access"))
<eul-subnav-resource inline-template>
    <label class="subnav-button -resource" @mouseenter="show" @mouseleave="hide">
        ${text}
        #if($options.contains("alias"))
        #set($subNavAlias = "")
        #set($subNavAlias = $headerMainNavLink.alias)
        <span class="subnav-button-alias">(${subNavAlias})</span>
        #end
        #if($options.contains("access")))
```

Note the triple parentheses at the end of the last line. Cascade sees that last `)` as text and is outputting it when it publishes the page. If HH searches for `)))`, they'll be able to find occurrences easily.

**Comment by rosy1280** [comment]
submitted to HH via wrike
