### ISSUE TITLE
Fix Main Nav menus overlapping at the tablet breakpoint

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#267]
Between 900px and 1200px, the main nav switches to a click/tap interface to expand the menus. If one menu is expanded while another is clicked, the first menu is not collapsed and the menus overlap.

See [INC03302641](https://emory.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=13c9598d1bde8418522e964ead4bcbfe%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)
## Screenshot
![Library site menu dropdown issue.png](https://images.zenhubusercontent.com/5b870487d5262f371e9eac64/00d94ab8-d0e3-41ef-82fc-a1587874e0a8)

**Comment by kristianserrano** [comment]
@rosy1280 the fix for this lies within the Velocity format for the header. Line 551 requires `@mouseover.stop="open"` and `@mouseleave.stop="close"` in the `label.nav-button` element. I've added the change to get the fix in place, but HH will want to incorporate that into their copy.

**Comment by rosy1280** [comment]
@kristianserrano can you confirm where you made the changes in cascade (i.e. is it in template assets)

**Comment by kristianserrano** [comment]
@rosy1280 The change was made here: https://cascade.emory.edu/entity/open.act?id=ac8dfc900ae7209815168d8a9ad6b4cd&type=format

**Comment by rosy1280** [comment]
ok cool.  HH doesn't have another copy, they were working from the template asset site.

**Comment by kristianserrano** [comment]
Ok, great. Previously, I was under the impression that if I made any changes, they were at risk of being overwritten by whatever HH puts in there after me. That led me to believe they might be developing in a different environment and copying and pasting into ours. Glad that's not the case.
