### ISSUE TITLE
Fix scrollbar appearing on About/Access links as they slide out in the Tools menu.

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#268]
When hovering over individual tools, the About/Access links temporarily display a scrollbar as they slide out.

See [INC03302641](https://emory.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=13c9598d1bde8418522e964ead4bcbfe%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

## Screenshot
![Library site scrollbar visible.png](https://images.zenhubusercontent.com/5b870487d5262f371e9eac64/ee136c23-8751-4f75-9dc7-0788adf25662)

**Comment by kristianserrano** [comment]
@rosy1280 I haven't been able to find a way yet to prevent the scrollbar from briefly displaying as the About/Access links slide out. I'm tempted to have the just appear without the transition, but I wanted to see if you were OK with that before I make that design change.

**Comment by rosy1280** [comment]
met.  reviewed.  decided: remove the slide out transition which is causing the scroll bar to appear.
