### ISSUE TITLE
Develop template architecture for global content

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#27]

**Comment by lovinscari** [comment]
@kristianserrano - Can you please confirm this issue is complete and can be closed? If not complete please estimate point value and determine if it can be completed in Sprint 9. Thanks!

**Comment by kristianserrano** [comment]
@lovinscari this is actually closeable. After talking with Lauren, we determined everything has been accounted for. We can't actually think of what work is remaining on this.
