### ISSUE TITLE
Services index page error

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-redesign#277]
On the [Services Index page](https://libraries.emory.edu/services/index.htm), the "Learn More" buttons for the following services do not connect to the intended external pages, but rather redirect to the top of the index page:

- Research Data Assistance
- Student Production Studio
- Music and Audio Recording Studio
- One Button Studio

These Learn More buttons link to external URLs rather than pages within the [Emory Libraries - Main site](https://libraries.emory.edu) which the remaining Learn More buttons link to.  The page needs to account for both internal and external URLs.

**Comment by rosy1280** [comment]
Hannon Hill fixed this issue
