### ISSUE TITLE
Custom Registration / R.S.V.P. link not appearing in event page.

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#278]
Some events use a text field for registration/RSVP URLs such as the one below.
![Screenshot 2020-03-06 at 3.05.44 PM.png](https://images.zenhubusercontent.com/5b870487d5262f371e9eac64/673dc8ef-f5ae-4cb7-a3d1-c6986b48826f)

These links are inserted into the JSON feed under `customFields`.
See `customFields` for event ID `143300098` in: https://www.trumba.com/calendars/robert-woodruff-library.json

Events using this field for registration links are not displaying the links.

Example event *with non-Trumba* registration link: https://libraries.emory.edu/events-exhibits/events/event.html?id=143364051

It seems that the event template is not using those fields but is only looking for Trumba-generated registration links. Events that do use the Trumba registration features display the button properly.

Example event *with Trumba* registration link: https://libraries.emory.edu/events-exhibits/events/event.html?id=141735484

This issue was reported by Maureen McGavin in [INC03340183](https://emory.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=e52e8a761bd7c8d0a8441f4ead4bcb99%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by kristianserrano** [comment]
Looking at the Vue component, it seems it's checking for `openSignUp === true && pastDeadline === false` and using `signUpUrl` only.

In the two cases in the ticket, both have `"openSignUp": false`.

**Comment by rosy1280** [comment]
@CB987 can you document here what you've uncovered in your research?

**Comment by CB987** [comment]
The pattern library file event.json organizes the data that comes in from the trumba feed (via event.js). It currently produces a button based on the criteria mentioned above, if openSignUp is true and pastDeadline is false. However, some of the events don't use the Trumba site sign-up option. In that case the event openSignUp will be false, but there will the the customFields 9959 with a link included. I can change the logic in the event.json to produce a button, with the appropriate link, based on the existence of customFields 9959, but I cannot get it to where it will choose which one to do based on the incoming data. It may be possible to do it by manipulating other elements of other files in the Pattern Library, but I haven't been able to figure it out. An alternate solution would be to ensure that the incoming data is consistent and always includes only the openSignUp field OR the customFields, and then we can set the appropriate logic to produce the button and link, without having the possibility of either being used.

**Comment by libdgg** [comment]
Blocked because we don't have sufficient workflows to accommodate registration links. They need to pick a way to register people.

**Comment by rosy1280** [comment]
Closing.  This will need to be addressed by CCR and Trumba workflows.
