### ISSUE TITLE
Complete Redirect Setup for Abandoned Links

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/web-redesign#281]
The following links never had redirection applied to them. I've created a ticket for LITS web team to complete the redirects to a 404 page per issue [343](https://app.zenhub.com/workspaces/website-redesign-5be9f5af4b5806bc2bf3ddda/issues/emory-libraries/pattern-library/343) that was closed earlier this year.
[INC03371160](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D0c6b41251b589458a8441f4ead4bcb63%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D79%26sysparm_record_list%3Dopened_by%253Djavascript%253Ags.getUserID%2528%2529%255Esys_class_name%2521%253Dsc_request%255Esys_class_name%2521%253Dsc_req_item%255EORDERBYDESCopened_at)

OLD LINKS THAT NEED A REDIRECT

/digital-library/index.html
/library-materials/collections/digitization.html
/library-materials/collections/gifts-in-kind.html
/library-materials/collections/index.html
/library-materials/collections/preservation-office.html

404 Page they should redirect to:
http://web.library.emory.edu/search/404.html

**Comment by rosy1280** [comment]
@libdgg is this something that still needs to be done?  now that we have an `.htaccess` file is it something i can do?

**Comment by libdgg** [comment]
@rosy1280 Closing this ticket since .htaccess is available now. Please reopen if you have concerns or other preferences for next steps.

Based on the RM and DG meeting to review redirects pon 2020-10-09, the next step would be to get with James to understand fully what is going on in the web server, how redirect.cfg and .htaccess files work together and their locations. We also see how things are setup for the new site (not just the old site) since we need to know to prepare for any future site work in cascade as well as any further incident work with redirects for the old site. Doug will touch base with Steve C. as a next step. 

Here is some info from today's meeting just in case its needed in the future:

OLD SITE SEEMS TO BE HERE
/var/www/docs/web.library.emory.edu

THE REDIRECT FILE FROM JAN-JUN 2020 SEEMS TO BE HERE
/etc/httpd/conf/redirect.cfg

THERE SEEMS TO BE A 301 REDIRECT VERSION OF THE FILE ALSO HERE
/etc/httpd/sites.d/rewrites/redirect.cfg

The htaccess should override the others? But it seems like redirects.cfg is first and if nothing is there then htaccess is invoked
/incoming/web.library.emory.edu/

**Comment by rosy1280** [comment]
more info: the original SN ticket referenced above said

> Here are some locations in our old library website < http://web.library.emory.edu/ > that need to have redirects to a 404 page. These pages do not have a corresponding match to the new website and the library web redesign project team determined that they should redirect to a 404. James Bias helped setup redirects for our website so he should have some background knowledge to help with this ticket. Please let me know if you have questions or next steps I should take. Thanks -Doug
> 
> OLD LINKS THAT NEED A REDIRECT
> 
> /digital-library/index.html
/library-materials/collections/digitization.html
/library-materials/collections/gifts-in-kind.html
/library-materials/collections/index.html
/library-materials/collections/preservation-office.html
> 
> 404 Page they should redirect to:
> http://web.library.emory.edu/search/404.html

We created a new .htaccess file that implements a 301 redirect for anything that doesn't have a redirect in the redirect.cfg file.
