### ISSUE TITLE
Update copyright statement to pull from the current year

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#282]
The copyright statement in the footer is currently statically entered into the HTML at Emory Template Assets > _cms > layout > .page_type_divs > footer

Ideally this information would be pulled from the current year the site (i.e. the year associated with the last publish date of any page on the site). this would need to be fixed by Hannon Hill in the velocity scripts for the website.

**Comment by LadySnowy** [comment]
@rosy1280 @cwbragg This has been updated to get the current year. The only code change was on line 135 of [this](https://cascade.emory.edu/entity/open.act?id=acabed400ae7209815168d8adc6ce07d&type=format) format.
