### ISSUE TITLE
Add Digital Collections search to "Intro Home" Organism

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#284]
## User Story
As an [end user of any type](https://wiki.service.emory.edu/display/DLPP/Demographic+%28Role-Based%29+Profiles), I would like to begin an Emory Digital Collections search from the Libraries website, so that I can discover additional types of material from a familiar entry point.

As a [library staff user](https://wiki.service.emory.edu/pages/viewpage.action?pageId=108801883), I would like to begin an Emory Digital Collections search from the Libraries website, so that I can provide a more cohesive resource discovery strategy for library users that I consult or instruct.

## Acceptance Criteria

- [x] 
Given that I am at libraries.emory.edu,
When I hover over the large search box,
Then, a clickable “DIGITAL COLLECTIONS” option appears among the others, between “EJOURNALS” and “RESEARCH AND COURSE GUIDES.”

- [x] 
Given that I am at hovering over the large search box at libraries.emory.edu,
When I click “DIGITAL COLLECTIONS,”
Then, the placeholder search text reads “Search Emory Digital Collections.”

- [x] 
Given that I have entered a search string into the “DIGITAL COLLECTIONS” option from the large search box at libraries.emory.edu,
When I press the enter key or click search,
Then a new tab appears on the digital.library.emory.edu domain with the search results page for the given string applied against Common Fields.

- [x] Current interaction patterns and styles are preserved in implementation.

## Mockup
![Group 9.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/4e1eb586-3f16-4d89-8c51-0fe6b91b2331)
[Link to pattern library organisms](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=viewall-organisms-all)

**Comment by rosy1280** [comment]
@wulman16 do you know if we ever deployed these changes (or the ones for #285 ) to the pattern library?  i'm not seeing them on the [homepage template in the pattern library](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home)

**Comment by wulman16** [comment]
@rosy1280 It looks like it made it into the intro-home organism (http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-intro-home), but I'm not seeing it in the template itself. I'll have to investigate further.

**Comment by rosy1280** [comment]
@wulman16 in thinking about this, at some point we should try to look into how to get it in the homepage template.  only for documentation purpose.  if you happen to have some down time at some point in time i'd appreciate it if you could look into it. but 1) don't kill yourself about it; and 2) don't make it a priority.

also i created a new ticket for this work in issue #290

**Comment by rosy1280** [comment]
For Hannon Hill:

Using the [intro-home organism](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-intro-home) in the pattern library, update the search box in the hero image on [the libraries' homepage](https://libraries.emory.edu) so that the users can also search the new digital library tab.
