### ISSUE TITLE
Add Digital Collections search to "Search Menu" Organism

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#285]
## User Story
As an [end user of any type](https://wiki.service.emory.edu/display/DLPP/Demographic+%28Role-Based%29+Profiles), I would like to begin an Emory Digital Collections search from the Libraries website, so that I can discover additional types of material from a familiar entry point.

As a [library staff user](https://wiki.service.emory.edu/pages/viewpage.action?pageId=108801883), I would like to begin an Emory Digital Collections search from the Libraries website, so that I can provide a more cohesive resource discovery strategy for library users that I consult or instruct.

## Acceptance Criteria

- [x] 
Given that I am on any page at libraries.emory.edu,
When I click the magnifying glass icon in the header,
Then, a clickable “DIGITAL COLLECTIONS” option appears among the others, between “EJOURNALS” and “RESEARCH AND COURSE GUIDES.”

- [x] 
Given that I have clicked the magnifying glass icon in the header on any page at libraries.emory.edu,
When I click “DIGITAL COLLECTIONS,”
Then, the placeholder search text reads “Search Emory Digital Collections.”

- [x] 
Given that I have entered a search string into the “DIGITAL COLLECTIONS” option from the large search box in the header search on any page,
When I press the enter key or click search,
Then a new tab appears on the digital.library.emory.edu domain with the search results page for the given string applied against Common Fields.

- [x] Current interaction patterns and styles are preserved in implementation.

## Mockup
![Search Databases.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/62f25790-81c4-4d6c-a315-c85dd3ada102)
[Link to pattern library organisms](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=viewall-organisms-all)

**Comment by rosy1280** [comment]
For Hannon Hill:

Using the [search-menu organism](https://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-search-menu) in the pattern library, update the search box in the navigation bar underneath the spyglass icon so that the users can also search the new digital library tab.
