### ISSUE TITLE
Update the search box in the hero image

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#292]
On the homepage the search box that appears in the hero image needs to also search the new emory digital collections.

Using the code from the [intro-home organism](https://template.library.emory.edu/styleguide/patternlibrary/current/patterns/50-organisms-intros-intro-home/50-organisms-intros-intro-home.html) in the pattern library, update the search box in the hero image to include the search tab for the [new digital collections site](https://digital.library.emory.edu/).

**Comment by LadySnowy** [comment]
@rosy1280 This is actually set up to be updatable without touching the code. The [search configuration page](https://cascade.emory.edu/entity/open.act?id=82fbd4580ae7209811020203d5497c70&type=page) is fairly user-friendly, just for future reference. Also, the digital collections will not load inside the inner Cascade page frame, but it does work on the full-screen preview version. I didn't publish so you'll just need to publish the home page for this to be live if it looks good.
