### ISSUE TITLE
Update the search box underneath the spyglass icon

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#293]
In the header, underneath the spyglass on the right hand side there is a search box that appears when you click on the spy glass 

Using the code in the [search-menu organism](https://template.library.emory.edu/styleguide/patternlibrary/current/patterns/50-organisms-navigation-search-menu/50-organisms-navigation-search-menu.html) in the pattern library, update the search box underneath the spyglass icon so that the users see the tab and can search the [new digital collections site](https://digital.library.emory.edu).

**Comment by LadySnowy** [comment]
@rosy1280 I incidentally updated this when I updated it for the home page, as they share the same search configurations. I believe just the [Main Navigation include page](https://cascade.emory.edu/entity/open.act?id=967c4e4c0ae72098248f13f39e4dc141&type=page) will need to be published in order for this to be live, if it looks good to you. Again, it only works on the full-screen preview page inside Cascade.
