### ISSUE TITLE
Update footer logo to new Emory Libraries logo

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#294]
Recently the Emory Libraries underwent a split from IT causing a rebranding of the organization.  The logo in the footer needs to be replaced to reflect the new branding.  

Acceptance criteria
- [ ] generate a svg logo using the linked logo files.  
   - ensure that the new svg logo matches similar dimensions and data as the existing one.
- [ ] replace the existing svg logo with the new svg logo.

[Zip package of logos](https://app.zenhub.com/files/159381045/2946d45b-d508-4636-a880-ec8d799bad9e/download).  Includes .eps, .pdf, .jpg, and .png formats

**Comment by LadySnowy** [comment]
@rosy1280 The new SVG logo is in place! I'll attach it here in case it is needed for anything else in the future.![Emory logo.svg](https://images.zenhubusercontent.com/5ffdd4bf28ca727dd430fb17/b8c7300e-e0b7-4398-bfdd-5fc2365aea2f)

**Comment by rosy1280** [comment]
@LadySnowy can you confirm where the logo lives in cascade so if we need to make future changes (i've heard that administration may choose to call us Emory UNIVERSITY Libraries) we know where to update it?

**Comment by LadySnowy** [comment]
@rosy1280 Yeah, the SVG is located in the [_cms/formats/_global/layout/footer format](https://cascade.emory.edu/entity/open.act?id=acabed400ae7209815168d8adc6ce07d&type=format&direct=true) on line 186.

**Comment by rosy1280** [comment]
Thanks!
