### ISSUE TITLE
Develop JS for pattern behavior

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#58]

**Comment by nikdragovic** [comment]
Revisit this issue - needs to be broken down by patterns (reference spreadsheet)

**Comment by kristianserrano** [comment]
Issue moved to [emory-libraries/Pattern-Library #106](https://github.com/emory-libraries/Pattern-Library/issues/106) via [**ZenHub**](https://www.zenhub.com/)
