### ISSUE TITLE
Create data definition for Bio Page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#68]

**Comment by nikdragovic** [comment]
Same page type is associated with SL page and staff directory. 

Returning for backlog in order to add field for LibCal.

**Comment by kristianserrano** [comment]
I added a `LibCal URL` field in the Contact Info group of the Employee Profile data definition.

In the future, if we have an enhancement to something we've already completed, I think we should add it as a new issue, label it as an enhancement, and if necessary, link the previous issue within the description. This will avoid confusion when we're looking at the titles of issues on the board. It will also allow us to estimate the enhancement separately from the original issue's estimate.

**Comment by kristianserrano** [comment]
@nikdragovic Please review and accept if you approve of the enhancement to the data definition.
