### ISSUE TITLE
Migrate News to Wordpress

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#7]
As a future improvement to how news is maintained, the current news instance should be ported over to a WordPress instance. This may or may not include the importing of archived news articles as well.

**Comment by laurenhamel** [comment]
@kristianserrano, for blogs and news, I assume we'll be pulling in these RSS feeds from WordPress in order to display their snippets on the news section's cover page. Is this correct?

**Comment by kristianserrano** [comment]
For the feeds, yes, but for individual stories that are featured, a standard external link will be used.
