### ISSUE TITLE
Create Content Type for Homepage

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#78]
- [x] Template
- [ ] Data Definition
- [x] Metadata Set
- [x] Configuration Set
- [ ] Base Asset
- [ ] Asset Factory

**Comment by laurenhamel** [comment]
@kristianserrano, this looks good. Some minor fixes needed before acceptance:
- Fix link customization checkboxes for all links
- Change default heading label for explorer box links
