### ISSUE TITLE
Verify preview server environment setup

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#9]
- open firewall and setup subdomain

**Comment by laurenhamel** [comment]
Is this in relation to the middleware work that already occurred in terms of getting servers setup? If so, then I think we can close this.

**Comment by kristianserrano** [comment]
It's ambiguously defined, but I suppose making sure QA and production are set up for public access (DNS changes, firewall, etc.) falls under this.

**Comment by laurenhamel** [comment]
This was completed and moved into Phase 2.
