### ISSUE TITLE
Create Content Type for Events and Exhibits in Utility Nav

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#92]
- [ ] Template
- [ ] Data Definition
- [ ] Metadata Set
- [ ] Configuration Set
- [ ] Base Asset
- [ ] Asset Factory

**Comment by laurenhamel** [comment]
Closing this as it's related to the templating engine workflow. A new issue will need to be opened in order to more accurately capture the work that needs to be done for #91.
