### ISSUE TITLE
Link to Ask a Librarian in Utility Nav

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#96]
- [x] Template
- [x] Data Definition
- [x] Metadata Set
- [x] Configuration Set
- [x] Base Asset
- [x] Asset Factory

**Comment by nikdragovic** [comment]
@kristianserrano Is this external link part of the header / utility nav work?

**Comment by laurenhamel** [comment]
This was completed and moved into Phase 2.
