### ISSUE TITLE
Create Content Type for About

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#97]
- [x] Template
- [x] Data Definition
- [x] Metadata Set
- [x] Configuration Set
- [x] Base Asset
- [x] Asset Factory

**Comment by kristianserrano** [comment]
@nikdragovic I've created a content type for utility nav links that covers this. We'll probably want to rename this to About.

**Comment by nikdragovic** [comment]
@kristianserrano I'm renaming this issue title to About, thanks!

**Comment by kristianserrano** [comment]
This is replaced by the work done in #98.
