### ISSUE TITLE
Create Content Type for Left Utility Nav Links

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#98]
- [x] Template
- [x] Data Definition
- [x] Metadata Set
- [x] Configuration Set
- [ ] Base Asset
- [ ] Asset Factory

**Comment by kristianserrano** [comment]
I've created a content type for utility nav links that covers this.

**Comment by kristianserrano** [comment]
We'll need to decide if these links are standard across all sites or customizable per site, or if there's even sites that won't have it at all in the future.

**Comment by kristianserrano** [comment]
I'm marking this as blocked until we have answers to these questions:
1. What content will be standard across all sites using the template?
2. What content will be customized per site?
3. What content will be applied only to the Emory Libraries site?

This could include links under “For Instructors”, or whether it even exists across all sites, as well as what dropdown options appear under Hours, Maps, Contact, etc.

**Comment by nikdragovic** [comment]
Decision to make everything customizable in utility nav.

**Comment by kristianserrano** [comment]
Relabeled this from "For Instructors" to "Left Utility Nav Links". This data definition/content type will allow for 1-2 groups of links, each with a custom label and a selection of links for each group/menu.

**Comment by nikdragovic** [comment]
Reviewed and accepted on 5/22.
